import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import TokenGuard from "./tokenGuard";        
import { GoogleOAuthProvider } from "@react-oauth/google";
const WEB_CLIENT_ID =
    "1011059979743-i8du42eeuof5fevob5gvtvl3fsiee1u3.apps.googleusercontent.com";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <GoogleOAuthProvider clientId={WEB_CLIENT_ID}> <TokenGuard>{children}</TokenGuard></GoogleOAuthProvider>
      </body>
    </html>
  );
}
